components:
  db:
    connectionString: 'mysql:host=localhost;dbname=drbl'
    emulatePrepare: true
    username: root
    password: tpinfo
    charset: utf8
params:
  drbl:
    save:
      partition:
      imageName:
      detect:
    restore:
      imageName:
      partition:
      wakeUpBefore:
      afterRestore:
      limitBandwidth:
      startNotReady:
  ldap:
    host: 192.168.49.3
    port: 389
    domain: ens-sfa.univ-poitiers.fr
  administration:
    adminEmail: franckuser16@gmail.com
    adminLogin: admin
