components:
  db:
    connectionString: 'mysql:host=localhost;dbname=drbl'
    emulatePrepare: true
    username: root
    password: tpinfo
    charset: utf8
params:
  drbl:
    save:
      partition: null
      imageName: null
      detect: null
    restore:
      imageName: null
      partition: null
      wakeUpBefore: null
      afterRestore: null
      limitBandwidth: null
      startNotReady: null
  ldap:
    host: 192.168.49.3
    port: 389
    domain: ens-sfa.univ-poitiers.fr
  administration:
    adminEmail: franckuser16@gmail.com
    adminLogin: admin
    adminSettings: '0'
